name: cdcine
description: O melhor streaming.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_inappwebview: ^6.0.0
  google_fonts: ^6.1.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1
  # --- NOVAS DEPENDÃŠNCIAS ADICIONADAS AQUI ---
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
