name: jinoca_stream
description: O melhor app de streaming.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Conexão com a Internet
  http: ^1.1.0
  # Player de Vídeo (Navegador Interno)
  webview_flutter: ^4.4.2
  # Fontes Bonitas
  google_fonts: ^6.1.0
  # Imagens com Cache (Carrega rápido)
  cached_network_image: ^3.3.0

flutter:
  uses-material-design: true
