name: cdcine
description: Streaming CDCINE.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  # ESSA É A NOVA BIBLIOTECA PODEROSA
  flutter_inappwebview: ^6.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1 # Para garantir permissões

flutter:
  uses-material-design: true
